// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBys99pns2E1CfKKwoiEUIWFnAvYyPUgvk',
    appId: '1:850021421455:web:81e84adf5c9fab810dfbfa',
    messagingSenderId: '850021421455',
    projectId: 'diary-app-9f1d5',
    authDomain: 'diary-app-9f1d5.firebaseapp.com',
    databaseURL: 'https://diary-app-9f1d5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diary-app-9f1d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLI4OtAkGKxS0VESZS_Y8loZz0m2L6Y-A',
    appId: '1:850021421455:android:867579157ae73c340dfbfa',
    messagingSenderId: '850021421455',
    projectId: 'diary-app-9f1d5',
    databaseURL: 'https://diary-app-9f1d5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diary-app-9f1d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk43mXMJOH9APEccywyBnOrWIg6fF6irQ',
    appId: '1:850021421455:ios:344dc5d6a938d3640dfbfa',
    messagingSenderId: '850021421455',
    projectId: 'diary-app-9f1d5',
    databaseURL: 'https://diary-app-9f1d5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diary-app-9f1d5.firebasestorage.app',
    iosClientId: '850021421455-s5ntqd64elv6dhm1csjkh0a5h3c9mp0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk43mXMJOH9APEccywyBnOrWIg6fF6irQ',
    appId: '1:850021421455:ios:344dc5d6a938d3640dfbfa',
    messagingSenderId: '850021421455',
    projectId: 'diary-app-9f1d5',
    databaseURL: 'https://diary-app-9f1d5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diary-app-9f1d5.firebasestorage.app',
    iosClientId: '850021421455-s5ntqd64elv6dhm1csjkh0a5h3c9mp0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBys99pns2E1CfKKwoiEUIWFnAvYyPUgvk',
    appId: '1:850021421455:web:c538125ff2ed57c30dfbfa',
    messagingSenderId: '850021421455',
    projectId: 'diary-app-9f1d5',
    authDomain: 'diary-app-9f1d5.firebaseapp.com',
    databaseURL: 'https://diary-app-9f1d5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diary-app-9f1d5.firebasestorage.app',
  );

}